---
title: "blog-post-1"
author: "Team 7"
date: "2024-03-04"
date-modified: "2024-03-04"
draft: FALSE
---

These are the descriptions of three data sets that we want to work with.


**Dataset 1: Death rates for suicide, by sex, race, Hispanic origin, and age: United States - Catalog**
https://catalog.data.gov/dataset/death-rates-for-suicide-by-sex-race-hispanic-origin-and-age-united-states-020c1
https://data.cdc.gov/NCHS/Death-rates-for-suicide-by-sex-race-Hispanic-origi/9j2v-jamp/about_data 

This datasets is about death rates for suicides across different combination of race, gender, age, and years. There are 6390 rows and 13 columns. Each row in this dataset represents a specific combination of race, gender, age, and year, for example, Female: White, or Male:Asian:65 years or order, and gives its suicide rate for the specific group. This data was originally collected by multiple organizations across many years from 1950 to 2019. It’s published by the National Center for Health Statistics. The data itself is already clean and available as a csv file. This dataset is outstanding as it concerns a lot of different demographic aspects, like race, gender, age, and year, which could be useful if we want to assess racial disparities and other issues with intersectionality. For example, we could compare groups with the same race but different gender, or same gender with different races, to explore more about racial disparities and how other demographics influence that. We would also be able to analyze the data longitudinal as it also provides changes over time for the same group. A potential challenge for this dataset could be the inconsistency of entities as they contain different numbers of demographic conditions (race and gender, or race, gender, and age), therefore more data cleaning might be necessary. 



**Dataset 2: Mental Health Care in the Last 4 Weeks**  
https://catalog.data.gov/dataset/mental-health-care-in-the-last-4-weeks

The "Mental Health Care in the Last 4 Weeks" dataset comprises 10,404 entries across 11 columns, derived from email and text message surveys. Its analysis is pivotal for investigating potential correlations between access to mental health services and suicide rates amidst the pandemic. However, the dataset poses a significant challenge due to the disorganized nature of its subgroup categorization, necessitating meticulous data cleaning and reorganization. Addressing this challenge is critical to ensuring the dataset accurately reflects the surveyed population, thereby enabling a meaningful examination of how mental health care impacts suicide trends during this unprecedented period.



**Dataset 3: Violence Reduction**  
https://catalog.data.gov/dataset/violence-reduction-victim-demographics-aggregated 

The “Violent Reduction” dataset primarily provides aggregate data on violent index victimizations in all 22 districts of Chicago at the quarter level of each year from 2001 to the present. The focus of this dataset is on gun related violence; it covers 10 crime types selected by the FBI (codes 1-4) for due to their seriousness and frequency. The dataset is refreshed daily, but excludes the most recent complete day to allow CPD time to gather the best available information. Moreover, it is critical to remember that this dataset is only based on crimes reported to the Chicago Police Department and is not all encompassing of crime in Chicago. Each row is aggregated up to victimization type, age group, sex, race, and whether the victimization was domestic-related. This dataset provides insights into the nature of victims and crime in Chicago and allows the CPD to keep a track of trends across time. There are several opportunities to clean the data including reassigning the names in the race variable and converting certain columns to binary variables. The main questions we could possibly address with this dataset include:   
- How does the rate and severity of violent victimizations vary by demographic characteristics such as age, race, ethnicity, gender, and domestic relationship?  
- How does the distribution and trend of violent victimizations change by geographic areas such as police districts, community areas, and neighborhoods?  
We can also tie this dataset to other available data on the nature of mental health and access to welfare in districts in Chicago and attempt to correlate it with trends in crime. The biggest challenges we might face include a lack of detailed demographic data, limited continuous variables, and some incomplete rows. 

